// Kompletna baza danych frontendu (Standalone Mock Database)
import { AlertMapItem } from '../components/AlertsMap';
import { User, Organization, Municipality } from '../types';

export interface MockResource {
  id: string;
  organizationId: string;
  type: 'ludzie' | 'woda' | 'sprzet' | 'inne';
  subcategory?: string | null;
  quantity: number;
  timeframe: '24h' | '48h' | '72h' | 'tydzien';
  isActive: boolean;
  organization?: {
    id: string;
    name: string;
    type: 'samorzad' | 'sluzby' | 'ngo';
    municipalityId: string;
  };
  createdAt: string;
}

export interface MockAuditLog {
  id: string;
  action: string;
  entityType: string;
  entityId: string;
  userId?: string | null;
  userName?: string | null;
  userEmail?: string | null;
  organizationId?: string | null;
  organizationName?: string | null;
  alertId?: string | null;
  alertTitle?: string | null;
  details: string;
  previousState?: any;
  newState?: any;
  isReverted: boolean;
  revertedAt?: string | null;
  revertedByUserId?: string | null;
  revertedByUserName?: string | null;
  createdAt: string;
}

export interface MockDatabase {
  municipalities: Municipality[];
  organizations: Organization[];
  users: User[];
  alerts: AlertMapItem[];
  resources: MockResource[];
  auditLogs: MockAuditLog[];
}

export const getInitialMockDatabase = (): MockDatabase => {
  const now = Date.now();
  const oneHour = 3600 * 1000;
  const oneMinute = 60 * 1000;

  // 1. Gminy i Miasta (20 jednostek samorządowych)
  const municipalities: Municipality[] = [
    { id: 'muni-1', name: 'Nowa Dęba' },
    { id: 'muni-2', name: 'Tarnobrzeg' },
    { id: 'muni-3', name: 'Baranów Sandomierski' },
    { id: 'muni-4', name: 'Gorzyce' },
    { id: 'muni-5', name: 'Grębów' },
    { id: 'muni-6', name: 'Majdan Królewski' },
    { id: 'muni-7', name: 'Kolbuszowa' },
    { id: 'muni-8', name: 'Cmolas' },
    { id: 'muni-9', name: 'Raniżów' },
    { id: 'muni-10', name: 'Stalowa Wola' },
    { id: 'muni-11', name: 'Bojanów' },
    { id: 'muni-12', name: 'Radomyśl nad Sanem' },
    { id: 'muni-13', name: 'Pysznica' },
    { id: 'muni-14', name: 'Nisko' },
    { id: 'muni-15', name: 'Rudnik nad Sanem' },
    { id: 'muni-16', name: 'Jeżowe' },
    { id: 'muni-17', name: 'Padew Narodowa' },
    { id: 'muni-18', name: 'Mielec' },
    { id: 'muni-19', name: 'Sandomierz' },
    { id: 'muni-20', name: 'Koprzywnica' },
  ];

  // 2. Organizacje (30 jednostek: samorządy, PSP, OSP, WOPR, PCK, NGO, WSP)
  const organizations: Organization[] = [
    { id: 'org-1', name: 'Urząd Miasta i Gminy Nowa Dęba', type: 'samorzad', municipalityId: 'muni-1' },
    { id: 'org-2', name: 'Ochotnicza Straż Pożarna w Nowej Dębie', type: 'sluzby', municipalityId: 'muni-1' },
    { id: 'org-3', name: 'Fundacja Pomocy Poszkodowanym Q - Oddział Podkarpacie', type: 'ngo', municipalityId: 'muni-1' },
    { id: 'org-4', name: 'Wojskowa Straż Pożarna OSPWL Nowa Dęba', type: 'sluzby', municipalityId: 'muni-1' },
    { id: 'org-5', name: 'Miejsko-Gminny Ośrodek Pomocy Społecznej Nowa Dęba', type: 'samorzad', municipalityId: 'muni-1' },
    { id: 'org-6', name: 'OSP Jadachy', type: 'sluzby', municipalityId: 'muni-1' },
    { id: 'org-7', name: 'OSP Chmielów', type: 'sluzby', municipalityId: 'muni-1' },
    { id: 'org-8', name: 'OSP Baranów Sandomierski', type: 'sluzby', municipalityId: 'muni-3' },
    { id: 'org-9', name: 'Gminny Sztab Zarządzania Kryzysowego Gorzyce', type: 'samorzad', municipalityId: 'muni-4' },
    { id: 'org-10', name: 'OSP Gorzyce', type: 'sluzby', municipalityId: 'muni-4' },
    { id: 'org-11', name: 'Komenda Miejska Państwowej Straży Pożarnej w Tarnobrzegu', type: 'sluzby', municipalityId: 'muni-2' },
    { id: 'org-12', name: 'Urząd Miasta Tarnobrzega - Wydział Bezpieczeństwa', type: 'samorzad', municipalityId: 'muni-2' },
    { id: 'org-13', name: 'Tarnobrzeskie WOPR - Baza Jezioro Tarnobrzeskie', type: 'sluzby', municipalityId: 'muni-2' },
    { id: 'org-14', name: 'Polski Czerwony Krzyż - Oddział Rejonowy w Tarnobrzegu', type: 'ngo', municipalityId: 'muni-2' },
    { id: 'org-15', name: 'Urząd Gminy Majdan Królewski', type: 'samorzad', municipalityId: 'muni-6' },
    { id: 'org-16', name: 'Ochotnicza Straż Pożarna w Majdanie Królewskim', type: 'sluzby', municipalityId: 'muni-6' },
    { id: 'org-17', name: 'Komenda Powiatowa PSP w Kolbuszowej', type: 'sluzby', municipalityId: 'muni-7' },
    { id: 'org-18', name: 'Starostwo Powiatowe w Kolbuszowej - Zespół ds. Zarządzania Kryzysowego', type: 'samorzad', municipalityId: 'muni-7' },
    { id: 'org-19', name: 'Komenda Powiatowa PSP w Stalowej Woli', type: 'sluzby', municipalityId: 'muni-10' },
    { id: 'org-20', name: 'Urząd Miasta Stalowa Wola', type: 'samorzad', municipalityId: 'muni-10' },
    { id: 'org-21', name: 'Harcerska Grupa Ratownicza ZHP Stalowa Wola', type: 'ngo', municipalityId: 'muni-10' },
    { id: 'org-22', name: 'OSP Bojanów', type: 'sluzby', municipalityId: 'muni-11' },
    { id: 'org-23', name: 'Komenda Powiatowa PSP w Nisku', type: 'sluzby', municipalityId: 'muni-14' },
    { id: 'org-24', name: 'OSP Rudnik nad Sanem', type: 'sluzby', municipalityId: 'muni-15' },
    { id: 'org-25', name: 'Komenda Powiatowa PSP w Mielcu', type: 'sluzby', municipalityId: 'muni-18' },
    { id: 'org-26', name: 'Stowarzyszenie Ratownictwa i Poszukiwań Mielec', type: 'ngo', municipalityId: 'muni-18' },
    { id: 'org-27', name: 'OSP Padew Narodowa', type: 'sluzby', municipalityId: 'muni-17' },
    { id: 'org-28', name: 'Komenda Powiatowa PSP w Sandomierzu', type: 'sluzby', municipalityId: 'muni-19' },
    { id: 'org-29', name: 'Wydział Spraw Obywatelskich i Zarządzania Kryzysowego UM Sandomierz', type: 'samorzad', municipalityId: 'muni-19' },
    { id: 'org-30', name: 'Świętokrzyski Sztab Ratownictwa Społecznego Sandomierz', type: 'ngo', municipalityId: 'muni-19' },
  ];

  // 3. Użytkownicy i Profile
  const users: User[] = [
    {
      id: 'usr-admin',
      firstName: 'Piotr',
      lastName: 'Administrator',
      email: 'admin@fundacjaq.pl',
      phone: '+48 500 100 100',
      role: 'admin',
      organizationId: 'org-3',
      isVerified: true,
      createdAt: new Date(now - 30 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-koord-nd',
      firstName: 'Tomasz',
      lastName: 'Dąbrowski',
      email: 'koordynator.nowadeba@samorzad.pl',
      phone: '+48 501 220 110',
      role: 'koordynator',
      organizationId: 'org-1',
      isVerified: true,
      createdAt: new Date(now - 25 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-koord-tb',
      firstName: 'Mariusz',
      lastName: 'Tarnowski',
      email: 'koordynator.tarnobrzeg@psp.pl',
      phone: '+48 502 330 220',
      role: 'koordynator',
      organizationId: 'org-11',
      isVerified: true,
      createdAt: new Date(now - 24 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-koord-kol',
      firstName: 'Grzegorz',
      lastName: 'Kolbusz',
      email: 'koordynator.kolbuszowa@powiat.pl',
      phone: '+48 503 440 330',
      role: 'koordynator',
      organizationId: 'org-17',
      isVerified: true,
      createdAt: new Date(now - 23 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-koord-sw',
      firstName: 'Wojciech',
      lastName: 'Stalowski',
      email: 'koordynator.stalowawola@stalowawola.pl',
      phone: '+48 504 550 440',
      role: 'koordynator',
      organizationId: 'org-20',
      isVerified: true,
      createdAt: new Date(now - 22 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-koord-san',
      firstName: 'Krzysztof',
      lastName: 'Sandomierski',
      email: 'koordynator.sandomierz@sandomierz.pl',
      phone: '+48 505 660 550',
      role: 'koordynator',
      organizationId: 'org-28',
      isVerified: true,
      createdAt: new Date(now - 21 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-koord-mie',
      firstName: 'Krzysztof',
      lastName: 'Mielecki',
      email: 'koordynator.mielec@psp.pl',
      phone: '+48 506 770 660',
      role: 'koordynator',
      organizationId: 'org-25',
      isVerified: true,
      createdAt: new Date(now - 20 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-osp-nd',
      firstName: 'Jan',
      lastName: 'Nowak',
      email: 'strazak.nowadeba@osp.pl',
      phone: '+48 601 112 233',
      role: 'czlonek',
      organizationId: 'org-2',
      isVerified: true,
      createdAt: new Date(now - 19 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-wsp-nd',
      firstName: 'Michał',
      lastName: 'Poligonowy',
      email: 'wsp.nowadeba@wojsko.pl',
      phone: '+48 602 223 344',
      role: 'czlonek',
      organizationId: 'org-4',
      isVerified: true,
      createdAt: new Date(now - 18 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-wopr-tb',
      firstName: 'Marcin',
      lastName: 'Wodny',
      email: 'ratownik.wopr@tarnobrzeg.pl',
      phone: '+48 603 334 455',
      role: 'czlonek',
      organizationId: 'org-13',
      isVerified: true,
      createdAt: new Date(now - 17 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-pck-tb',
      firstName: 'Sylwia',
      lastName: 'Zielińska',
      email: 'wolontariusz.pck@tarnobrzeg.pl',
      phone: '+48 604 445 566',
      role: 'czlonek',
      organizationId: 'org-14',
      isVerified: true,
      createdAt: new Date(now - 16 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-rat-mie',
      firstName: 'Damian',
      lastName: 'Sikora',
      email: 'ratownik.mielec@med.pl',
      phone: '+48 605 556 677',
      role: 'czlonek',
      organizationId: 'org-26',
      isVerified: true,
      createdAt: new Date(now - 15 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-osp-maj',
      firstName: 'Paweł',
      lastName: 'Królewski',
      email: 'strazak.majdan@osp.pl',
      phone: '+48 606 667 788',
      role: 'czlonek',
      organizationId: 'org-16',
      isVerified: true,
      createdAt: new Date(now - 14 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-hgr-sw',
      firstName: 'Mateusz',
      lastName: 'Harcerski',
      email: 'hgr.stalowawola@zhp.pl',
      phone: '+48 607 112 233',
      role: 'czlonek',
      organizationId: 'org-21',
      isVerified: true,
      createdAt: new Date(now - 13 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-pending-1',
      firstName: 'Karolina',
      lastName: 'Majdańska',
      email: 'nowy.ochotnik@majdan.pl',
      phone: '+48 607 778 899',
      role: 'czlonek',
      organizationId: 'org-15',
      isVerified: false,
      createdAt: new Date(now - 2 * 24 * oneHour).toISOString(),
    },
    {
      id: 'usr-pending-2',
      firstName: 'Krzysztof',
      lastName: 'Bojanowski',
      email: 'krzysztof.bojanow@osp.pl',
      phone: '+48 608 889 900',
      role: 'czlonek',
      organizationId: 'org-22',
      isVerified: false,
      createdAt: new Date(now - 1 * 24 * oneHour).toISOString(),
    },
  ];

  // Powiązanie relacji dla userów
  users.forEach((u) => {
    const org = organizations.find((o) => o.id === u.organizationId);
    if (org) {
      const muni = municipalities.find((m) => m.id === org.municipalityId);
      u.organization = {
        ...org,
        municipality: muni,
      };
    }
  });

  // 4. Pełne 15 Alertów ze wszystkimi postami i wiadomościami czatu
  const alerts: AlertMapItem[] = [
    // 1. Nowa Dęba - Pożar
    {
      id: 'alt-1',
      title: 'Pożar poszycia leśnego na obrzeżach Poligonu OSPWL Nowa Dęba',
      content: 'W wyniku silnych porywów wiatru i posuchy doszło do rozprzestrzenienia się ognia w sektorze leśnym D-12 w pobliżu drogi DK9. Zagrożona ściana lasu w kierunku osiedla Dęba. Na miejscu działają jednostki WSP, OSP Nowa Dęba, OSP Jadachy oraz zadysponowano samolot gaśniczy Dromader.',
      category: 'Pożar i Zagrożenie Ogniowe',
      severity: 'krytyczny',
      isActive: true,
      authorId: 'usr-koord-nd',
      municipalityId: 'muni-1',
      locationName: 'Nowa Dęba (Poligon OSPWL)',
      county: 'powiat tarnobrzeski',
      voivodeship: 'podkarpackie',
      lat: 50.4320,
      lng: 21.7650,
      createdAt: new Date(now - 4 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-nd',
        firstName: 'Tomasz',
        lastName: 'Dąbrowski',
        role: 'koordynator',
        organization: { id: 'org-1', name: 'Urząd Miasta i Gminy Nowa Dęba', type: 'samorzad' },
      },
      municipality: { id: 'muni-1', name: 'Nowa Dęba' },
      history: [
        {
          id: 'hist-1',
          action: 'created',
          timestamp: new Date(now - 4 * oneHour).toISOString(),
          userName: 'Tomasz Dąbrowski',
          organizationName: 'Urząd Miasta i Gminy Nowa Dęba',
          details: 'Utworzenie alertu pożarowego na poligonie',
        },
      ],
      neededResources: [
        {
          id: 'nr-nd-1',
          resourceType: 'sprzet',
          name: 'Cysterny gaśnicze i zbiorniki brezentowe na wodę (>5000L)',
          quantityNeeded: 6,
          quantityAllocated: 4,
          unit: 'szt.',
          urgency: 'krytyczny',
          allocations: [
            {
              id: 'al-nd-1',
              organizationId: 'org-4',
              organizationName: 'Wojskowa Straż Pożarna OSPWL Nowa Dęba',
              userId: 'usr-wsp-nd',
              userName: 'Michał Poligonowy',
              quantity: 2,
              allocatedAt: new Date(now - 3 * oneHour).toISOString(),
              note: 'Cysterny wojskowe Jelcz skierowane na odcinek północny',
            },
            {
              id: 'al-nd-2',
              organizationId: 'org-2',
              organizationName: 'Ochotnicza Straż Pożarna w Nowej Dębie',
              userId: 'usr-osp-nd',
              userName: 'Jan Nowak',
              quantity: 2,
              allocatedAt: new Date(now - 2 * oneHour).toISOString(),
              note: 'Wóz gaśniczy GCBA z remizy Nowa Dęba',
            },
          ],
        },
        {
          id: 'nr-nd-2',
          resourceType: 'ludzie',
          name: 'Strażacy z uprawnieniami do gaszenia pożarów wielkopowierzchniowych',
          quantityNeeded: 40,
          quantityAllocated: 25,
          unit: 'strażaków',
          urgency: 'krytyczny',
          allocations: [
            {
              id: 'al-nd-3',
              organizationId: 'org-11',
              organizationName: 'Komenda Miejska Państwowej Straży Pożarnej w Tarnobrzegu',
              userId: 'usr-koord-tb',
              userName: 'Mariusz Tarnowski',
              quantity: 15,
              allocatedAt: new Date(now - 3 * oneHour).toISOString(),
              note: 'Sekcja gaśnicza JRG 1 Tarnobrzeg',
            },
            {
              id: 'al-nd-4',
              organizationId: 'org-16',
              organizationName: 'Ochotnicza Straż Pożarna w Majdanie Królewskim',
              userId: 'usr-osp-maj',
              userName: 'Paweł Królewski',
              quantity: 10,
              allocatedAt: new Date(now - 2 * oneHour).toISOString(),
              note: 'Dwa zastępy OSP Majdan Królewski ze sprzętem tłumiącym',
            },
          ],
        },
        {
          id: 'nr-nd-3',
          resourceType: 'woda',
          name: 'Woda butelkowana i elektrolity dla ratowników w strefie zero',
          quantityNeeded: 800,
          quantityAllocated: 800,
          unit: 'butelek 1.5L',
          urgency: 'wysoki',
          allocations: [
            {
              id: 'al-nd-5',
              organizationId: 'org-3',
              organizationName: 'Fundacja Pomocy Poszkodowanym Q - Oddział Podkarpacie',
              userId: 'usr-admin',
              userName: 'Piotr Administrator',
              quantity: 800,
              allocatedAt: new Date(now - 2 * oneHour).toISOString(),
              note: 'Dostarczono 800 butelek wody i izotoniki prosto do punktu medycznego',
            },
          ],
        },
        {
          id: 'nr-nd-4',
          resourceType: 'sprzet',
          name: 'Drony termowizyjne do lokalizacji zarzewi ognia z powietrza',
          quantityNeeded: 3,
          quantityAllocated: 2,
          unit: 'zestawy',
          urgency: 'wysoki',
          allocations: [
            {
              id: 'al-nd-6',
              organizationId: 'org-26',
              organizationName: 'Stowarzyszenie Ratownictwa i Poszukiwań Mielec',
              userId: 'usr-rat-mie',
              userName: 'Damian Sikora',
              quantity: 2,
              allocatedAt: new Date(now - 1 * oneHour).toISOString(),
              note: 'Operatorzy z dronami DJI Matrice 300 RTK z termowizją w akcji',
            },
          ],
        },
      ],
      posts: [
        {
          id: 'post-nd-1',
          authorId: 'usr-koord-nd',
          authorName: 'Tomasz Dąbrowski',
          organizationName: 'Urząd Miasta i Gminy Nowa Dęba',
          role: 'koordynator',
          title: 'Sytuacja opanowana w strefie przy ul. Bieszczadzkiej',
          content: 'Dzięki wsparciu samolotu Lasów Państwowych i odcięciu pasa pożarowego przez spychacze z poligonu linia ognia nie zagraża już bezpośrednio zabudowaniom mieszkalnym. Trwa dogaszanie ściółki.',
          postType: 'komunikat_sztabowy',
          createdAt: new Date(now - 3 * oneHour).toISOString(),
          messages: [
            {
              id: 'msg-nd-1a',
              authorId: 'usr-osp-nd',
              authorName: 'Jan Nowak',
              organizationName: 'OSP Nowa Dęba',
              role: 'czlonek',
              content: 'Przejęliśmy sektor wschodni od strony Jadachów. Potrzebujemy dodatkowej linii wężowej W-75 do zasilania działka wodnego.',
              createdAt: new Date(now - 2 * oneHour - 45 * oneMinute).toISOString(),
            },
            {
              id: 'msg-nd-1b',
              authorId: 'usr-wsp-nd',
              authorName: 'Michał Poligonowy',
              organizationName: 'WSP OSPWL Nowa Dęba',
              role: 'czlonek',
              content: 'Wóz GCBA z bazy poligonowej dowozi 8 odcinków W-75 i rozdzielacz. Będziemy na skrzyżowaniu leśnym za 5 minut.',
              createdAt: new Date(now - 2 * oneHour - 38 * oneMinute).toISOString(),
            },
            {
              id: 'msg-nd-1c',
              authorId: 'usr-rat-mie',
              authorName: 'Damian Sikora',
              organizationName: 'Stowarzyszenie Ratownictwa Mielec',
              role: 'czlonek',
              content: 'Podgląd z kamery termowizyjnej drona: w kwadracie D-14 widzimy jeszcze dwa podziemne punkty żarzenia torfu o temperaturze ~280°C. Wysyłam koordynaty GPS bezpośrednio do dyspozytora.',
              createdAt: new Date(now - 2 * oneHour - 15 * oneMinute).toISOString(),
            },
            {
              id: 'msg-nd-1d',
              authorId: 'usr-koord-nd',
              authorName: 'Tomasz Dąbrowski',
              organizationName: 'Urząd Miasta i Gminy Nowa Dęba',
              role: 'koordynator',
              content: 'Dziękuję za precyzyjne namiary. Zadysponowałem tam zastęp OSP Majdan Królewski ze szpadlami i prądami gaśniczymi.',
              createdAt: new Date(now - 2 * oneHour - 5 * oneMinute).toISOString(),
            },
          ],
        },
        {
          id: 'post-nd-2',
          authorId: 'usr-wsp-nd',
          authorName: 'Michał Poligonowy',
          organizationName: 'Wojskowa Straż Pożarna OSPWL Nowa Dęba',
          role: 'czlonek',
          title: 'Wsparcie logistyczne bazy wojskowej - punkt tankowania',
          content: 'Uruchomiliśmy punkt tankowania wody w bazie poligonowej przy bramie nr 3. Wszystkie wozy OSP i PSP mogą bez kolejki uzupełniać zbiorniki z hydrantów wysokociśnieniowych jednostki.',
          postType: 'logistyka',
          createdAt: new Date(now - 2 * oneHour).toISOString(),
          messages: [
            {
              id: 'msg-nd-2a',
              authorId: 'usr-admin',
              authorName: 'Piotr Administrator',
              organizationName: 'Fundacja Pomocy Poszkodowanym Q',
              role: 'admin',
              content: 'Fundacja Q rozstawiła przy bramie nr 3 namiot socjalny z ciepłą kawą, herbatą, posiłkami regeneracyjnymi i suchym prowiantem dla wszystkich powracających rot.',
              createdAt: new Date(now - 1 * oneHour - 40 * oneMinute).toISOString(),
            },
            {
              id: 'msg-nd-2b',
              authorId: 'usr-osp-maj',
              authorName: 'Paweł Królewski',
              organizationName: 'OSP Majdan Królewski',
              role: 'czlonek',
              content: 'Świetna robota z tym punktem, ratownicy po 4 godzinach w dymie bardzo doceniają ciepły posiłek i wodę!',
              createdAt: new Date(now - 1 * oneHour - 10 * oneMinute).toISOString(),
            },
          ],
        },
        {
          id: 'post-nd-3',
          authorId: 'usr-rat-mie',
          authorName: 'Damian Sikora',
          organizationName: 'Stowarzyszenie Ratownictwa i Poszukiwań Mielec',
          role: 'czlonek',
          title: 'Raport z powietrza - monitoring granicy lasu i torowiska LHS',
          content: 'Zakończyliśmy 45-minutowy oblot wzdłuż linii kolejowej LHS. Brak zadymienia w pobliżu składów towarowych. Wiatr osłabł do 2 m/s w kierunku południowym.',
          postType: 'raport_terenowy',
          createdAt: new Date(now - 45 * oneMinute).toISOString(),
          messages: [
            {
              id: 'msg-nd-3a',
              authorId: 'usr-koord-nd',
              authorName: 'Tomasz Dąbrowski',
              organizationName: 'Urząd Miasta i Gminy Nowa Dęba',
              role: 'koordynator',
              content: 'Przyjąłem. Utrzymujemy dozór nocny 2 wozów OSP Jadachy do rana.',
              createdAt: new Date(now - 20 * oneMinute).toISOString(),
            },
          ],
        },
      ],
    },

    // 2. Nowa Dęba - Ujęcie wody
    {
      id: 'alt-2',
      title: 'Skażenie biologiczne ujęcia wody i awaria magistrali - osiedla Centrum i Północ',
      content: 'Wykryto przekroczenie parametrów mikrobiologicznych w wodociągu miejskim zaopatrującym około 8 000 mieszkańców Nowej Dęby. Woda niezdatna do spożycia nawet po przegotowaniu. Uruchomiono punkty dystrybucji wody pitnej pod Samorządowym Ośrodkiem Kultury oraz Szpitalem Powiatowym.',
      category: 'Skażenie i awaria infrastruktury',
      severity: 'wysoki',
      isActive: true,
      authorId: 'usr-koord-nd',
      municipalityId: 'muni-1',
      locationName: 'Nowa Dęba (Centrum i Osiedle Północ)',
      county: 'powiat tarnobrzeski',
      voivodeship: 'podkarpackie',
      lat: 50.4261,
      lng: 21.7505,
      createdAt: new Date(now - 10 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-nd',
        firstName: 'Tomasz',
        lastName: 'Dąbrowski',
        role: 'koordynator',
        organization: { id: 'org-1', name: 'Urząd Miasta i Gminy Nowa Dęba', type: 'samorzad' },
      },
      municipality: { id: 'muni-1', name: 'Nowa Dęba' },
      neededResources: [
        {
          id: 'nr-nd-w-1',
          resourceType: 'woda',
          name: 'Woda pitna w baniakach 5L i paletach dla ludności',
          quantityNeeded: 12000,
          quantityAllocated: 8500,
          unit: 'litrów',
          urgency: 'krytyczny',
          allocations: [
            {
              id: 'al-nd-w1',
              organizationId: 'org-3',
              organizationName: 'Fundacja Pomocy Poszkodowanym Q - Oddział Podkarpacie',
              userId: 'usr-admin',
              userName: 'Piotr Administrator',
              quantity: 5000,
              allocatedAt: new Date(now - 6 * oneHour).toISOString(),
              note: 'Dostawa 10 palet wody z hubu logistycznego',
            },
            {
              id: 'al-nd-w2',
              organizationId: 'org-14',
              organizationName: 'Polski Czerwony Krzyż w Tarnobrzegu',
              userId: 'usr-pck-tb',
              userName: 'Sylwia Zielińska',
              quantity: 3500,
              allocatedAt: new Date(now - 4 * oneHour).toISOString(),
              note: 'Woda ze stacji rezerw PCK przekazana do MGOPS',
            },
          ],
        },
        {
          id: 'nr-nd-w-2',
          resourceType: 'ludzie',
          name: 'Wolontariusze do rozwożenia wody osobom starszym i niepełnosprawnym',
          quantityNeeded: 25,
          quantityAllocated: 18,
          unit: 'wolontariuszy',
          urgency: 'wysoki',
          allocations: [
            {
              id: 'al-nd-w3',
              organizationId: 'org-5',
              organizationName: 'MGOPS Nowa Dęba',
              userId: 'usr-koord-nd',
              userName: 'Tomasz Dąbrowski',
              quantity: 18,
              allocatedAt: new Date(now - 5 * oneHour).toISOString(),
              note: 'Pracownicy socjalni i harcerze na liście dyżurów domowych',
            },
          ],
        },
        {
          id: 'nr-nd-w-3',
          resourceType: 'sprzet',
          name: 'Mobilne beczkowozy atestowane do wody pitnej',
          quantityNeeded: 4,
          quantityAllocated: 3,
          unit: 'pojazdy',
          urgency: 'wysoki',
          allocations: [
            {
              id: 'al-nd-w4',
              organizationId: 'org-1',
              organizationName: 'Urząd Miasta i Gminy Nowa Dęba',
              userId: 'usr-koord-nd',
              userName: 'Tomasz Dąbrowski',
              quantity: 3,
              allocatedAt: new Date(now - 7 * oneHour).toISOString(),
              note: 'Beczkowozy rozstawione: ul. Żeromskiego, ul. Krasickiego, Szpital',
            },
          ],
        },
      ],
      posts: [
        {
          id: 'post-nd-w-1',
          authorId: 'usr-koord-nd',
          authorName: 'Tomasz Dąbrowski',
          organizationName: 'Urząd Miasta i Gminy Nowa Dęba',
          role: 'koordynator',
          title: 'Harmonogram podstawiania beczkowozów i punkty stałe',
          content: 'Beczkowozy będą uzupełniane co 3 godziny. Sanepid pobrał ponowne próbki - wyniki płukania sieci i chlorowania ujęcia spodziewane jutro do godziny 12:00.',
          postType: 'komunikat_sztabowy',
          createdAt: new Date(now - 6 * oneHour).toISOString(),
          messages: [
            {
              id: 'msg-nd-w1a',
              authorId: 'usr-pck-tb',
              authorName: 'Sylwia Zielińska',
              organizationName: 'Polski Czerwony Krzyż Tarnobrzeg',
              role: 'czlonek',
              content: 'Nasz zespół dostarczył już 120 zgrzewek wody 5L dla oddziałów wewnętrznego i pediatrii Szpitala Powiatowego w Nowej Dębie.',
              createdAt: new Date(now - 5 * oneHour - 20 * oneMinute).toISOString(),
            },
            {
              id: 'msg-nd-w1b',
              authorId: 'usr-admin',
              authorName: 'Piotr Administrator',
              organizationName: 'Fundacja Pomocy Poszkodowanym Q',
              role: 'admin',
              content: 'Mamy na stanie dodatkowe 6 palet wody butelkowanej na magazynie w Tarnobrzegu. Jeśli zajdzie potrzeba dowozu na osiedle Północ, nasz bus jest w gotowości.',
              createdAt: new Date(now - 4 * oneHour - 50 * oneMinute).toISOString(),
            },
          ],
        },
        {
          id: 'post-nd-w-2',
          authorId: 'usr-pck-tb',
          authorName: 'Sylwia Zielińska',
          organizationName: 'Polski Czerwony Krzyż w Tarnobrzegu',
          role: 'czlonek',
          title: 'Akcja pomocy osobom leżącym i seniorom - Osiedle Północ',
          content: 'Wolontariusze PCK wraz z harcerzami odwiedzili 47 adresów seniorów z listy MGOPS. Każdy otrzymał zapas wody pitnej na 48h oraz tabletki do dezynfekcji naczyń.',
          postType: 'raport_terenowy',
          createdAt: new Date(now - 2 * oneHour).toISOString(),
          messages: [],
        },
      ],
    },

    // 3. Tarnobrzeg - Wisła i Wielowieś
    {
      id: 'alt-3',
      title: 'Czoło fali powodziowej na Wiśle w rejonie Tarnobrzega i Sandomierza',
      content: 'Stan Wisły na wodowskazie w Sandomierzu przekroczył stan ostrzegawczy o 80 cm i rośnie w tempie 12 cm/h. Prowadzone jest patrolowanie i podwyższanie korony wałów w rejonie osiedli Wielowieś, Sielec i Zakrzów. Przygotowano stacje workowania piasku.',
      category: 'Ostrzeżenie hydrologiczne',
      severity: 'krytyczny',
      isActive: true,
      authorId: 'usr-koord-tb',
      municipalityId: 'muni-2',
      locationName: 'Tarnobrzeg (Osiedle Wielowieś / Sielec)',
      county: 'Tarnobrzeg',
      voivodeship: 'podkarpackie',
      lat: 50.6015,
      lng: 21.6850,
      createdAt: new Date(now - 8 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-tb',
        firstName: 'Mariusz',
        lastName: 'Tarnowski',
        role: 'koordynator',
        organization: { id: 'org-11', name: 'Komenda Miejska PSP w Tarnobrzegu', type: 'sluzby' },
      },
      municipality: { id: 'muni-2', name: 'Tarnobrzeg' },
      neededResources: [
        {
          id: 'nr-tb-1',
          resourceType: 'inne',
          name: 'Worki jutowe i polipropylenowe na piasek',
          quantityNeeded: 20000,
          quantityAllocated: 16000,
          unit: 'szt.',
          urgency: 'krytyczny',
          allocations: [
            {
              id: 'al-tb-1',
              organizationId: 'org-12',
              organizationName: 'Urząd Miasta Tarnobrzega',
              userId: 'usr-koord-tb',
              userName: 'Mariusz Tarnowski',
              quantity: 10000,
              allocatedAt: new Date(now - 6 * oneHour).toISOString(),
              note: 'Wydano z magazynu przeciwpowodziowego miasta',
            },
            {
              id: 'al-tb-2',
              organizationId: 'org-3',
              organizationName: 'Fundacja Pomocy Poszkodowanym Q - Oddział Podkarpacie',
              userId: 'usr-admin',
              userName: 'Piotr Administrator',
              quantity: 6000,
              allocatedAt: new Date(now - 4 * oneHour).toISOString(),
              note: 'Przerzut rezerw materiałowych z Nowej Dęby do Tarnobrzega',
            },
          ],
        },
        {
          id: 'nr-tb-2',
          resourceType: 'sprzet',
          name: 'Wysokowydajne pompy powodziowe ciągnikowe i spalinowe (>6000 l/min)',
          quantityNeeded: 8,
          quantityAllocated: 5,
          unit: 'agregatów',
          urgency: 'wysoki',
          allocations: [
            {
              id: 'al-tb-3',
              organizationId: 'org-11',
              organizationName: 'Komenda Miejska Państwowej Straży Pożarnej w Tarnobrzegu',
              userId: 'usr-koord-tb',
              userName: 'Mariusz Tarnowski',
              quantity: 3,
              allocatedAt: new Date(now - 5 * oneHour).toISOString(),
              note: 'Agregaty pompowe z JRG Tarnobrzeg',
            },
          ],
        },
      ],
      posts: [
        {
          id: 'post-tb-1',
          authorId: 'usr-koord-tb',
          authorName: 'Mariusz Tarnowski',
          organizationName: 'Komenda Miejska PSP w Tarnobrzegu',
          role: 'koordynator',
          title: 'Stan wałów stabilny, wzmocniono newralgiczne przepusty',
          content: 'Zakończono układanie rękawa przeciwpowodziowego o długości 600m w rejonie wału rzeki Trześniówka. Sytuacja pod stałym monitoringiem patroli pieszych i dronów.',
          postType: 'raport_terenowy',
          createdAt: new Date(now - 5 * oneHour).toISOString(),
          messages: [
            {
              id: 'msg-tb-1a',
              authorId: 'usr-wopr-tb',
              authorName: 'Marcin Wodny',
              organizationName: 'Tarnobrzeskie WOPR',
              role: 'czlonek',
              content: 'Baza WOPR przy Jeziorze Tarnobrzeskim postawiła 3 załogi w stan gotowości natychmiastowej. Łodzie i quady z przyczepkami są zatankowane pod korek.',
              createdAt: new Date(now - 4 * oneHour - 10 * oneMinute).toISOString(),
            },
          ],
        },
      ],
    },

    // 4. Majdan Królewski - Nawałnica
    {
      id: 'alt-4',
      title: 'Skutki gwałtownego frontu burzowego - zerwane dachy i zatarasowana DK9',
      content: 'Przejście superkomórki burzowej spowodowało zerwanie 14 dachów na budynkach mieszkalnych i gospodarczych w Majdanie Królewskim, Hucie Komorowskiej i Krzątce. Powalone drzewa zablokowały trasę DK9 w kierunku Kolbuszowej. Trwają prace udrażniające i zabezpieczanie plandekami.',
      category: 'Zagrożenie meteorologiczne',
      severity: 'wysoki',
      isActive: true,
      authorId: 'usr-koord-kol',
      municipalityId: 'muni-6',
      locationName: 'Majdan Królewski (Huta Komorowska / Krzątka)',
      county: 'powiat kolbuszowski',
      voivodeship: 'podkarpackie',
      lat: 50.3667,
      lng: 21.7458,
      createdAt: new Date(now - 6 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-kol',
        firstName: 'Grzegorz',
        lastName: 'Kolbusz',
        role: 'koordynator',
        organization: { id: 'org-17', name: 'Komenda Powiatowa PSP w Kolbuszowej', type: 'sluzby' },
      },
      municipality: { id: 'muni-6', name: 'Majdan Królewski' },
      neededResources: [
        {
          id: 'nr-mk-1',
          resourceType: 'inne',
          name: 'Plandeki budowlane zbrojone (10x15m, 12x20m) do zabezpieczenia dachów',
          quantityNeeded: 45,
          quantityAllocated: 30,
          unit: 'szt.',
          urgency: 'krytyczny',
          allocations: [
            {
              id: 'al-mk-1',
              organizationId: 'org-18',
              organizationName: 'Starostwo Kolbuszowa',
              userId: 'usr-koord-kol',
              userName: 'Grzegorz Kolbusz',
              quantity: 20,
              allocatedAt: new Date(now - 4 * oneHour).toISOString(),
              note: 'Wydano z rezerwy magazynu powiatowego',
            },
          ],
        },
        {
          id: 'nr-mk-2',
          resourceType: 'sprzet',
          name: 'Agregaty prądotwórcze jednofazowe i trójfazowe dla gospodarstw bez prądu',
          quantityNeeded: 15,
          quantityAllocated: 10,
          unit: 'agregatów',
          urgency: 'wysoki',
          allocations: [
            {
              id: 'al-mk-3',
              organizationId: 'org-16',
              organizationName: 'Ochotnicza Straż Pożarna w Majdanie Królewskim',
              userId: 'usr-osp-maj',
              userName: 'Paweł Królewski',
              quantity: 4,
              allocatedAt: new Date(now - 4 * oneHour).toISOString(),
              note: 'Zasilenie aparatury medycznej u pacjentów domowych w Krzątce',
            },
          ],
        },
      ],
      posts: [
        {
          id: 'post-mk-1',
          authorId: 'usr-koord-kol',
          authorName: 'Grzegorz Kolbusz',
          organizationName: 'Komenda Powiatowa PSP w Kolbuszowej',
          role: 'koordynator',
          title: 'Trasa DK9 odblokowana, ruch wahadłowy w Hucie Komorowskiej',
          content: 'Strażacy usunęli 28 powalonych wiatrołomów. Energetyka pracuje nad odbudową zerwanej linii średniego napięcia.',
          postType: 'komunikat_sztabowy',
          createdAt: new Date(now - 4 * oneHour).toISOString(),
          messages: [
            {
              id: 'msg-mk-1a',
              authorId: 'usr-osp-maj',
              authorName: 'Paweł Królewski',
              organizationName: 'OSP Majdan Królewski',
              role: 'czlonek',
              content: 'W Hucie Komorowskiej zabezpieczyliśmy 5 domów plandekami przed spodziewanym nocnym deszczem. Zostały jeszcze 2 stodoły z zerwanym poszyciem.',
              createdAt: new Date(now - 3 * oneHour - 15 * oneMinute).toISOString(),
            },
          ],
        },
      ],
    },

    // 5. Bojanów - Rzeka Łęg
    {
      id: 'alt-5',
      title: 'Przybór wód rzeki Łęg w gminie Bojanów i cofka do Sanu',
      content: 'Rzeka Łęg wystąpiła z koryta w miejscowościach Bojanów, Stany i Przyszów. Podtopionych zostało 18 posesji oraz lokalne drogi gminne. Zorganizowano doraźny punkt ewakuacji zwierząt hodowlanych w wyżej położonych zabudowaniach OSP Stany.',
      category: 'Ostrzeżenie hydrologiczne',
      severity: 'wysoki',
      isActive: true,
      authorId: 'usr-koord-sw',
      municipalityId: 'muni-11',
      locationName: 'Bojanów (Dolina rzeki Łęg)',
      county: 'powiat stalowowolski',
      voivodeship: 'podkarpackie',
      lat: 50.4194,
      lng: 21.9639,
      createdAt: new Date(now - 12 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-sw',
        firstName: 'Wojciech',
        lastName: 'Stalowski',
        role: 'koordynator',
        organization: { id: 'org-20', name: 'Urząd Miasta Stalowa Wola', type: 'samorzad' },
      },
      municipality: { id: 'muni-11', name: 'Bojanów' },
      neededResources: [
        {
          id: 'nr-boj-1',
          resourceType: 'sprzet',
          name: 'Pompy szlamowe pływające i wysokowydajne motopompy',
          quantityNeeded: 10,
          quantityAllocated: 7,
          unit: 'szt.',
          urgency: 'wysoki',
          allocations: [
            {
              id: 'al-boj-1',
              organizationId: 'org-19',
              organizationName: 'Komenda Powiatowa PSP w Stalowej Woli',
              userId: 'usr-koord-sw',
              userName: 'Wojciech Stalowski',
              quantity: 4,
              allocatedAt: new Date(now - 8 * oneHour).toISOString(),
              note: 'Zadysponowano pompy pływające Niagara',
            },
          ],
        },
      ],
      posts: [
        {
          id: 'post-boj-1',
          authorId: 'usr-koord-sw',
          authorName: 'Wojciech Stalowski',
          organizationName: 'Urząd Miasta Stalowa Wola',
          role: 'koordynator',
          title: 'Woda w korycie Łęgu zaczyna powoli opadać',
          content: 'Kulminacja przeszła przez Bojanów w godzinach porannych. Przystępujemy do wypompowywania wody z piwnic i studni przydomowych.',
          postType: 'raport_terenowy',
          createdAt: new Date(now - 4 * oneHour).toISOString(),
          messages: [],
        },
      ],
    },

    // 6. Koprzywnica / Sandomierz - Koprzywianka
    {
      id: 'alt-6',
      title: 'Utrzymanie reżimu przeciwpowodziowego w dolinie rzeki Koprzywianki',
      content: 'Intensywny spływ wód opadowych z Wyżyny Sandomierskiej podniósł poziom rzeki Koprzywianki w gminach Koprzywnica i Samborzec. Zagrożone są tereny upraw sadowniczych oraz lokalne przepompownie melioracyjne. Pracują 4 stacjonarne pompy odwadniające.',
      category: 'Ostrzeżenie hydrologiczne',
      severity: 'średni',
      isActive: true,
      authorId: 'usr-koord-san',
      municipalityId: 'muni-20',
      locationName: 'Koprzywnica / Samborzec',
      county: 'powiat sandomierski',
      voivodeship: 'świętokrzyskie',
      lat: 50.5908,
      lng: 21.5122,
      createdAt: new Date(now - 14 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-san',
        firstName: 'Krzysztof',
        lastName: 'Sandomierski',
        role: 'koordynator',
        organization: { id: 'org-28', name: 'Komenda Powiatowa PSP w Sandomierzu', type: 'sluzby' },
      },
      municipality: { id: 'muni-20', name: 'Koprzywnica' },
      neededResources: [
        {
          id: 'nr-san-1',
          resourceType: 'sprzet',
          name: 'Paliwo do agregatów i ciągników pompujących (olej napędowy)',
          quantityNeeded: 2000,
          quantityAllocated: 1500,
          unit: 'litrów',
          urgency: 'wysoki',
        },
      ],
      posts: [
        {
          id: 'post-san-1',
          authorId: 'usr-koord-san',
          authorName: 'Krzysztof Sandomierski',
          organizationName: 'KP PSP Sandomierz',
          role: 'koordynator',
          title: 'Przepompownie pracują z pełną wydajnością',
          content: 'Dostarczone paliwo zabezpiecza ciągłość pracy agregatów na kolejne 36 godzin. Lustro wody w rowach opaskowych obniżyło się o 15 cm.',
          postType: 'komunikat_sztabowy',
          createdAt: new Date(now - 6 * oneHour).toISOString(),
          messages: [],
        },
      ],
    },

    // 7. Padew Narodowa - Poszukiwania Babule
    {
      id: 'alt-7',
      title: 'Akcja poszukiwawczo-ratownicza w kompleksie leśnym Padew Narodowa - Babule',
      content: 'Trwają poszukiwania 74-letniego grzybiarza, który od wczorajszego popołudnia nie powrócił do miejsca zamieszkania. W akcji biorą udział przewodnicy z psami tropiącymi, quady, drony z kamerą noktowizyjną oraz ratownicy Stowarzyszenia Poszukiwawczego z Mielca i OSP Padew.',
      category: 'Akcja poszukiwawczo-ratownicza',
      severity: 'wysoki',
      isActive: true,
      authorId: 'usr-koord-nd',
      municipalityId: 'muni-17',
      locationName: 'Padew Narodowa / Kompleks Leśny Babule',
      county: 'powiat mielecki',
      voivodeship: 'podkarpackie',
      lat: 50.4350,
      lng: 21.5036,
      createdAt: new Date(now - 7 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-nd',
        firstName: 'Tomasz',
        lastName: 'Dąbrowski',
        role: 'koordynator',
        organization: { id: 'org-1', name: 'Urząd Miasta i Gminy Nowa Dęba', type: 'samorzad' },
      },
      municipality: { id: 'muni-17', name: 'Padew Narodowa' },
      neededResources: [
        {
          id: 'nr-mie-1',
          resourceType: 'ludzie',
          name: 'Ratownicy z uprawnieniami poszukiwawczymi i łącznością GPS/VHF',
          quantityNeeded: 30,
          quantityAllocated: 24,
          unit: 'ratowników',
          urgency: 'krytyczny',
        },
      ],
      posts: [
        {
          id: 'post-mie-1',
          authorId: 'usr-rat-mie',
          authorName: 'Damian Sikora',
          organizationName: 'Stowarzyszenie Ratownictwa i Poszukiwań Mielec',
          role: 'czlonek',
          title: 'Odnaleziono ślady w sektorze leśnym 48B',
          content: 'Pies tropiący podjął trop w stronę leśniczówki Babule. Zacieśniamy kwadrat poszukiwań do obszaru 2x2 km.',
          postType: 'raport_terenowy',
          createdAt: new Date(now - 3 * oneHour).toISOString(),
          messages: [],
        },
      ],
    },

    // 8. Rudnik nad Sanem - Most kolejowy
    {
      id: 'alt-8',
      title: 'Zator z pni drzew i gałęzi pod filarami mostu kolejowego na Sanie w Rudniku',
      content: 'Duże nagromadzenie naniesionych konarów i pni stworzyło barierę spiętrzającą wodę rzeki San o 1.2 m w górę biegu. Na miejscu pracują płetwonurkowie, dźwig samojezdny oraz liny holownicze z wciągarkami ciężkimi.',
      category: 'Komunikat drogowy',
      severity: 'średni',
      isActive: true,
      authorId: 'usr-koord-sw',
      municipalityId: 'muni-15',
      locationName: 'Rudnik nad Sanem (Most kolejowy na Sanie)',
      county: 'powiat niżański',
      voivodeship: 'podkarpackie',
      lat: 50.4431,
      lng: 22.2411,
      createdAt: new Date(now - 16 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-sw',
        firstName: 'Wojciech',
        lastName: 'Stalowski',
        role: 'koordynator',
        organization: { id: 'org-20', name: 'Urząd Miasta Stalowa Wola', type: 'samorzad' },
      },
      municipality: { id: 'muni-15', name: 'Rudnik nad Sanem' },
      neededResources: [],
      posts: [],
    },

    // 9. Nowa Dęba / Rozalin - Dębianka
    {
      id: 'alt-9',
      title: 'Podtopienia posesji i zalanie drogi lokalnej po gwałtownych opadach - Rozalin / Jadachy',
      content: 'Potok Dębianka wystąpił z koryta po nawalnych opadach deszczu (68 mm/3h). Woda wdarła się na teren 14 posesji prywatnych oraz zalała odcinek drogi powiatowej Rozalin-Jadachy na długości 400 m. Strażacy prowadzą pompowanie wody i układanie zapór workowych wokół budynków gospodarczych.',
      category: 'Ostrzeżenie hydrologiczne',
      severity: 'krytyczny',
      isActive: true,
      authorId: 'usr-koord-nd',
      municipalityId: 'muni-1',
      locationName: 'Nowa Dęba (Rozalin / Jadachy)',
      county: 'powiat tarnobrzeski',
      voivodeship: 'podkarpackie',
      lat: 50.4480,
      lng: 21.7250,
      createdAt: new Date(now - 3 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-nd',
        firstName: 'Tomasz',
        lastName: 'Dąbrowski',
        role: 'koordynator',
        organization: { id: 'org-1', name: 'Urząd Miasta i Gminy Nowa Dęba', type: 'samorzad' },
      },
      municipality: { id: 'muni-1', name: 'Nowa Dęba' },
      neededResources: [
        {
          id: 'nr-roz-1',
          resourceType: 'sprzet',
          name: 'Pompy szlamowe dużej wydajności (>1200 l/min) z wężami ssawnymi',
          quantityNeeded: 6,
          quantityAllocated: 4,
          unit: 'szt.',
          urgency: 'krytyczny',
          allocations: [
            {
              id: 'al-roz-1',
              organizationId: 'org-2',
              organizationName: 'OSP Nowa Dęba',
              userId: 'usr-osp-nd',
              userName: 'Jan Nowak',
              quantity: 2,
              allocatedAt: new Date(now - 2 * oneHour).toISOString(),
              note: 'Pompy szlamowe Honda wysłane z przyczepą powodziową',
            },
          ],
        },
      ],
      posts: [
        {
          id: 'post-roz-1',
          authorId: 'usr-koord-nd',
          authorName: 'Tomasz Dąbrowski',
          organizationName: 'Urząd Miasta i Gminy Nowa Dęba',
          role: 'koordynator',
          title: 'Sytuacja hydrologiczna w zlewni Dębianki',
          content: 'Woda w rowach melioracyjnych przestała przybierać, jednak przepust drogowy w Rozalinie jest zablokowany gałęziami. Ciężki sprzęt komunalny udrażnia koryto.',
          postType: 'komunikat_sztabowy',
          createdAt: new Date(now - 2 * oneHour).toISOString(),
          messages: [],
        },
      ],
    },

    // 10. Baranów Sandomierski - Suchorzów wał
    {
      id: 'alt-10',
      title: 'Przesiąkanie podstawy wału przeciwpowodziowego Wisły - Suchorzów / Dymitrów',
      content: 'Wzmożony napór fali wezbraniowej na 145. kilometrze Wisły spowodował pojawienie się przesiąków i wysięków dennych na zawalu w Suchorzowie. Konieczne jest dociążenie stopy wału workami z piaskiem oraz geowłókniną filtracyjną.',
      category: 'Ostrzeżenie hydrologiczne',
      severity: 'krytyczny',
      isActive: true,
      authorId: 'usr-koord-tb',
      municipalityId: 'muni-3',
      locationName: 'Baranów Sandomierski (Suchorzów)',
      county: 'powiat tarnobrzeski',
      voivodeship: 'podkarpackie',
      lat: 50.5050,
      lng: 21.5420,
      createdAt: new Date(now - 6 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-tb',
        firstName: 'Mariusz',
        lastName: 'Tarnowski',
        role: 'koordynator',
        organization: { id: 'org-11', name: 'Komenda Miejska PSP w Tarnobrzegu', type: 'sluzby' },
      },
      municipality: { id: 'muni-3', name: 'Baranów Sandomierski' },
      neededResources: [
        {
          id: 'nr-bar-1',
          resourceType: 'sprzet',
          name: 'Geowłóknina filtracyjna oraz rękawy przeciwpowodziowe napełniane wodą',
          quantityNeeded: 8,
          quantityAllocated: 5,
          unit: 'kpl.',
          urgency: 'krytyczny',
        },
      ],
      posts: [],
    },

    // 11. Gorzyce - Wrzawy widły Wisły i Sanu
    {
      id: 'alt-11',
      title: 'Kulminacja fali powodziowej na Sanie i zjawisko cofki do koryta rzeki Łęg',
      content: 'Rzeka San osiągnęła poziom 615 cm (stan alarmowy przekroczony o 95 cm). Występuje silne spiętrzenie wsteczne wpadającego dopływu Łęg. Pompownia melioracyjna w Zalesiu Gorzyckim pracuje na maksymalnej wydajności 4 agregatów.',
      category: 'Ostrzeżenie hydrologiczne',
      severity: 'krytyczny',
      isActive: true,
      authorId: 'usr-koord-tb',
      municipalityId: 'muni-4',
      locationName: 'Gorzyce (Wrzawy - widły Wisły i Sanu)',
      county: 'powiat tarnobrzeski',
      voivodeship: 'podkarpackie',
      lat: 50.6650,
      lng: 21.8320,
      createdAt: new Date(now - 5 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-tb',
        firstName: 'Mariusz',
        lastName: 'Tarnowski',
        role: 'koordynator',
        organization: { id: 'org-11', name: 'Komenda Miejska PSP w Tarnobrzegu', type: 'sluzby' },
      },
      municipality: { id: 'muni-4', name: 'Gorzyce' },
      neededResources: [],
      posts: [],
    },

    // 12. Radomyśl nad Sanem - Czekaj Pniowski
    {
      id: 'alt-12',
      title: 'Zalanie międzywala Sanu i odcięcie dojazdu do przeprawy promowej w Radomyślu',
      content: 'Rzeka San zalała drogę dojazdową do promu na trasie Radomyśl nad Sanem - Antoniów. Woda podeszła pod zabudowania gospodarcze w sołectwie Czekaj Pniowski. Trwa monitorowanie wałów bocznych i zabezpieczanie ujęć wody technologicznej.',
      category: 'Ostrzeżenie hydrologiczne',
      severity: 'wysoki',
      isActive: true,
      authorId: 'usr-koord-sw',
      municipalityId: 'muni-12',
      locationName: 'Radomyśl nad Sanem (Czekaj Pniowski / San)',
      county: 'powiat stalowowolski',
      voivodeship: 'podkarpackie',
      lat: 50.6820,
      lng: 21.9450,
      createdAt: new Date(now - 7 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-sw',
        firstName: 'Wojciech',
        lastName: 'Stalowski',
        role: 'koordynator',
        organization: { id: 'org-20', name: 'Urząd Miasta Stalowa Wola', type: 'samorzad' },
      },
      municipality: { id: 'muni-12', name: 'Radomyśl nad Sanem' },
      neededResources: [],
      posts: [],
    },

    // 13. Padew Narodowa - Wisłoka
    {
      id: 'alt-13',
      title: 'Podwyższony stan rzeki Wisłoki i cofka do rowów melioracyjnych w Padwi Narodowej',
      content: 'Wisłoka osiągnęła stan ostrzegawczy na stacji Mielec. W rejonie Padwi Narodowej woda zablokowała spływ wód opadowych, co powoduje zalewanie łąk i pól uprawnych na obszarze ponad 80 hektarów. Zagrożone są 3 budynki inwentarskie.',
      category: 'Ostrzeżenie hydrologiczne',
      severity: 'średni',
      isActive: true,
      authorId: 'usr-koord-mie',
      municipalityId: 'muni-17',
      locationName: 'Padew Narodowa (Dolina Wisłoki)',
      county: 'powiat mielecki',
      voivodeship: 'podkarpackie',
      lat: 50.4410,
      lng: 21.5030,
      createdAt: new Date(now - 9 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-mie',
        firstName: 'Krzysztof',
        lastName: 'Mielecki',
        role: 'koordynator',
        organization: { id: 'org-25', name: 'Komenda Powiatowa PSP w Mielcu', type: 'sluzby' },
      },
      municipality: { id: 'muni-17', name: 'Padew Narodowa' },
      neededResources: [],
      posts: [],
    },

    // 14. Gorzyce - Odwołany alarm (Archiwalny)
    {
      id: 'alt-14',
      title: 'Pomyślne zakończenie prac prewencyjnych w węźle wodnym Gorzyce / Wrzawy',
      content: 'Zakończono przegląd i doszczelnienie śluz wałowych w rejonie ujścia Sanu do Wisły w miejscowości Wrzawy. Wszystkie zasuwy pracują prawidłowo, poziom wód powrócił do strefy stanów średnich. Alarm odwołany.',
      category: 'Informacja ogólna',
      severity: 'niski',
      isActive: false,
      authorId: 'usr-koord-tb',
      municipalityId: 'muni-4',
      locationName: 'Gorzyce (Wrzawy - widły Wisły i Sanu)',
      county: 'powiat tarnobrzeski',
      voivodeship: 'podkarpackie',
      lat: 50.6720,
      lng: 21.8290,
      createdAt: new Date(now - 36 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-tb',
        firstName: 'Mariusz',
        lastName: 'Tarnowski',
        role: 'koordynator',
        organization: { id: 'org-11', name: 'Komenda Miejska PSP w Tarnobrzegu', type: 'sluzby' },
      },
      municipality: { id: 'muni-4', name: 'Gorzyce' },
      neededResources: [],
      posts: [],
    },

    // 15. Kolbuszowa - Gazociąg (Archiwalny)
    {
      id: 'alt-15',
      title: 'Usunięcie nieszczelności gazociągu średniego ciśnienia przy ul. Towarowej',
      content: 'Pogotowie Gazowe w asyście KP PSP Kolbuszowa zakończyło naprawę uszkodzonego rurociągu. Mieszkańcy ewakuowanych 6 budynków powrócili bezpiecznie do domów. Ruch na skrzyżowaniu przywrócony.',
      category: 'Skażenie i awaria infrastruktury',
      severity: 'niski',
      isActive: false,
      authorId: 'usr-koord-kol',
      municipalityId: 'muni-7',
      locationName: 'Kolbuszowa (ul. Towarowa)',
      county: 'powiat kolbuszowski',
      voivodeship: 'podkarpackie',
      lat: 50.2431,
      lng: 21.7709,
      createdAt: new Date(now - 48 * oneHour).toISOString(),
      author: {
        id: 'usr-koord-kol',
        firstName: 'Grzegorz',
        lastName: 'Kolbusz',
        role: 'koordynator',
        organization: { id: 'org-17', name: 'Komenda Powiatowa PSP w Kolbuszowej', type: 'sluzby' },
      },
      municipality: { id: 'muni-7', name: 'Kolbuszowa' },
      neededResources: [],
      posts: [],
    },
  ];

  // 5. Rozbudowane Zasoby Magazynowe (Warehouse Matrix)
  const resources: MockResource[] = [
    // Nowa Dęba
    { id: 'res-1', organizationId: 'org-2', type: 'sprzet', subcategory: 'Motopompy szlamowe Honda / Tohatsu', quantity: 6, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-2', organizationId: 'org-2', type: 'inne', subcategory: 'Worki z piaskiem wzmacniane', quantity: 3000, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-3', organizationId: 'org-2', type: 'ludzie', subcategory: 'Strażacy ratownicy KSRG z uprawnieniami', quantity: 22, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-4', organizationId: 'org-4', type: 'sprzet', subcategory: 'Ciężkie wozy gaśnicze i cysterny terenowe', quantity: 4, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-5', organizationId: 'org-4', type: 'ludzie', subcategory: 'Wojskowa załoga gaśniczo-ratownicza', quantity: 16, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-6', organizationId: 'org-3', type: 'woda', subcategory: 'Zgrzewki wody pitnej 1.5L i 5L', quantity: 10000, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-7', organizationId: 'org-3', type: 'ludzie', subcategory: 'Wolontariusze pomocy humanitarnej i psycholog', quantity: 35, timeframe: '48h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-8', organizationId: 'org-3', type: 'inne', subcategory: 'Koce termiczne, łóżka polowe, śpiwory', quantity: 450, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },

    // Tarnobrzeg
    { id: 'res-9', organizationId: 'org-11', type: 'sprzet', subcategory: 'Wysokowydajne pompy powodziowe (>6000 l/min)', quantity: 6, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-10', organizationId: 'org-11', type: 'ludzie', subcategory: 'Obsada ratownicza JRG 1 Tarnobrzeg', quantity: 30, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-11', organizationId: 'org-13', type: 'sprzet', subcategory: 'Łodzie ratownicze płaskodenne i skuter wodny z deską', quantity: 8, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-12', organizationId: 'org-13', type: 'ludzie', subcategory: 'Ratownicy wodni MSWiA i płetwonurkowie', quantity: 18, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-13', organizationId: 'org-14', type: 'woda', subcategory: 'Baniaki z atestem i pakiety uzdatniania', quantity: 6000, timeframe: '48h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-14', organizationId: 'org-14', type: 'inne', subcategory: 'Pakiety żywnościowe długoterminowe MRE', quantity: 1200, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },

    // Majdan Królewski & Kolbuszowa
    { id: 'res-15', organizationId: 'org-16', type: 'sprzet', subcategory: 'Agregaty prądotwórcze dużej mocy', quantity: 5, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-16', organizationId: 'org-16', type: 'ludzie', subcategory: 'Ratownicy OSP ze sprzętem pilarskim', quantity: 15, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-17', organizationId: 'org-17', type: 'sprzet', subcategory: 'Podnośnik hydrauliczny SHD-25 i piły do betonu', quantity: 3, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },

    // Stalowa Wola & Nisko & Mielec
    { id: 'res-18', organizationId: 'org-19', type: 'sprzet', subcategory: 'Maszty oświetleniowe LED ze stacją prądotwórczą', quantity: 8, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-19', organizationId: 'org-26', type: 'sprzet', subcategory: 'Drony termowizyjne i quady 4x4', quantity: 6, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-20', organizationId: 'org-26', type: 'ludzie', subcategory: 'Przewodnicy z certyfikowanymi psami ratowniczymi', quantity: 8, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-21', organizationId: 'org-21', type: 'inne', subcategory: 'Wodery, nosze koszowe i apteczki polowe', quantity: 40, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
    { id: 'res-22', organizationId: 'org-24', type: 'sprzet', subcategory: 'Pilarki łańcuchowe spalinowe Stihl / Husqvarna', quantity: 10, timeframe: '24h', isActive: true, createdAt: new Date(now - 10 * 24 * oneHour).toISOString() },
  ];

  // 6. Logi audytowe
  const auditLogs: MockAuditLog[] = [
    {
      id: 'log-1',
      action: 'alert_created',
      entityType: 'alert',
      entityId: 'alt-1',
      userId: 'usr-koord-nd',
      userName: 'Tomasz Dąbrowski',
      userEmail: 'koordynator.nowadeba@samorzad.pl',
      alertId: 'alt-1',
      alertTitle: 'Pożar poszycia leśnego na obrzeżach Poligonu OSPWL Nowa Dęba',
      details: 'Utworzenie i publikacja komunikatu: "Pożar poszycia leśnego na obrzeżach Poligonu OSPWL Nowa Dęba" w lokalizacji Nowa Dęba (Poligon OSPWL)',
      isReverted: false,
      createdAt: new Date(now - 4 * oneHour).toISOString(),
    },
    {
      id: 'log-2',
      action: 'resource_allocated',
      entityType: 'resource',
      entityId: 'nr-nd-1',
      userId: 'usr-wsp-nd',
      userName: 'Michał Poligonowy',
      userEmail: 'wsp.nowadeba@wojsko.pl',
      alertId: 'alt-1',
      alertTitle: 'Pożar poszycia leśnego na obrzeżach Poligonu OSPWL Nowa Dęba',
      details: 'Dyspozycja zasobów: przekazano 2 szt. na zapotrzebowanie "Cysterny gaśnicze i zbiorniki brezentowe na wodę (>5000L)"',
      isReverted: false,
      createdAt: new Date(now - 3 * oneHour).toISOString(),
    },
    {
      id: 'log-3',
      action: 'alert_created',
      entityType: 'alert',
      entityId: 'alt-2',
      userId: 'usr-koord-nd',
      userName: 'Tomasz Dąbrowski',
      userEmail: 'koordynator.nowadeba@samorzad.pl',
      alertId: 'alt-2',
      alertTitle: 'Skażenie biologiczne ujęcia wody i awaria magistrali - osiedla Centrum i Północ',
      details: 'Utworzenie i publikacja komunikatu o awarii i skażeniu wody',
      isReverted: false,
      createdAt: new Date(now - 10 * oneHour).toISOString(),
    },
  ];

  // Populating organization on all resources
  const populatedResources: MockResource[] = resources.map((r) => {
    const org = organizations.find((o) => o.id === r.organizationId);
    return {
      ...r,
      organization: org,
    };
  });

  return {
    municipalities,
    organizations,
    users,
    alerts,
    resources: populatedResources,
    auditLogs,
  };
};
